# Тестовые задания. Каримов Ильдар

## Задание № 1 (Numpy):

1. Создать двумерный массив из случайных чисел от 0 до 1 размером 10х10 и вывести на экран.
2. Найти индекс (номер строки и номер столбца) максимального элемента.
3. Переставить столбцы так, чтобы в первой строке массива значения шли по возрастанию.
4. Отнормировать значения в каждой строке (то есть для каждой строки найти сумму элементов
и разделить на эту сумму каждый элемент строки).
5. Заменить значения массива, которые больше 0.5, на -1.
6. Вывести полученный массив на экран.

## Решение: 

### 1. Создать двумерный массив из случайных чисел от 0 до 1 размером 10х10 и вывести на экран.

In [1]:
# Импортируем необходимые библиотеки

import pandas as pd
import numpy as np
import random

In [2]:
rand_arr = np.random.rand(10, 10) # cоздаем двумерный массив из случайных чисел 
rand_arr # выведем на экран массив 

array([[0.01494671, 0.26784111, 0.73564703, 0.7928289 , 0.35879919,
        0.48984194, 0.45510777, 0.71235012, 0.58639025, 0.92987274],
       [0.18742289, 0.58944913, 0.73700371, 0.31279591, 0.20361336,
        0.19103163, 0.9304043 , 0.60791211, 0.17244599, 0.80085909],
       [0.33880104, 0.06812755, 0.36638936, 0.59431975, 0.24763867,
        0.96378141, 0.23587707, 0.14350379, 0.92513938, 0.98335575],
       [0.99278947, 0.89691442, 0.97194182, 0.91941503, 0.10998635,
        0.13655423, 0.01684885, 0.3700023 , 0.31830107, 0.36938285],
       [0.62055257, 0.06301992, 0.70949104, 0.15924636, 0.45829939,
        0.1590671 , 0.2414054 , 0.8134093 , 0.8093624 , 0.54075964],
       [0.11064655, 0.31510357, 0.82507805, 0.72762919, 0.36288231,
        0.43668227, 0.75539312, 0.62055912, 0.22013681, 0.86084108],
       [0.44780935, 0.17133765, 0.53906078, 0.35348242, 0.35338184,
        0.52940239, 0.67883587, 0.99761862, 0.84995219, 0.49936885],
       [0.53300155, 0.15819531, 0.5868271

### 2. Найти индекс (номер строки и номер столбца) максимального элемента.

In [3]:
# запишем функция для нахождения индекса двумерного массива 

def find_max_index(a_1):
    max_element = a_1[0][0]
    max_row, max_col = 0, 0
    for row in range(len(a_1)):
        for col in range(len(a_1[row])):
            if a_1[row][col] > max_element:
                max_element = a_1[row][col]
                max_row, max_col = row, col
    return max_row, max_col

max_row, max_col = find_max_index(rand_arr)
print("Максимальный элемент находится в строке", max_row, "и в столбце", max_col) # выведем на экран строки и столбца

Максимальный элемент находится в строке 6 и в столбце 7


### 3. Переставить столбцы так, чтобы в первой строке массива значения шли по возрастанию.

In [4]:
rand_arr = rand_arr[::, rand_arr[0,].argsort()[::1]] # отсортируем массив с помощью функции argsort() 

In [5]:
rand_arr # проверим сортировку 

array([[0.01494671, 0.26784111, 0.35879919, 0.45510777, 0.48984194,
        0.58639025, 0.71235012, 0.73564703, 0.7928289 , 0.92987274],
       [0.18742289, 0.58944913, 0.20361336, 0.9304043 , 0.19103163,
        0.17244599, 0.60791211, 0.73700371, 0.31279591, 0.80085909],
       [0.33880104, 0.06812755, 0.24763867, 0.23587707, 0.96378141,
        0.92513938, 0.14350379, 0.36638936, 0.59431975, 0.98335575],
       [0.99278947, 0.89691442, 0.10998635, 0.01684885, 0.13655423,
        0.31830107, 0.3700023 , 0.97194182, 0.91941503, 0.36938285],
       [0.62055257, 0.06301992, 0.45829939, 0.2414054 , 0.1590671 ,
        0.8093624 , 0.8134093 , 0.70949104, 0.15924636, 0.54075964],
       [0.11064655, 0.31510357, 0.36288231, 0.75539312, 0.43668227,
        0.22013681, 0.62055912, 0.82507805, 0.72762919, 0.86084108],
       [0.44780935, 0.17133765, 0.35338184, 0.67883587, 0.52940239,
        0.84995219, 0.99761862, 0.53906078, 0.35348242, 0.49936885],
       [0.53300155, 0.15819531, 0.3380387

### 4. Отнормировать значения в каждой строке (то есть для каждой строки найти сумму элементов и разделить на эту сумму каждый элемент строки).

In [6]:
rand_arr_normalized = rand_arr/rand_arr.sum(axis=1) # делим каждый элемент на сумму элементов 

In [10]:
rand_arr_normalized # выведем отнормированный массив на экран 

array([[0.00279711, 0.05659088, 0.07372182, 0.08919945, 0.10707833,
        0.11201444, 0.13142385, 0.15721133, 0.17995854, 0.20698463],
       [0.0350741 , 0.12454191, 0.04183606, 0.18235583, 0.04175908,
        0.03294127, 0.11215573, 0.15750126, 0.0709993 , 0.17826689],
       [0.06340284, 0.01439435, 0.05088187, 0.04623104, 0.21068042,
        0.17672356, 0.02647549, 0.07829918, 0.13490037, 0.21888966],
       [0.18578948, 0.18950479, 0.02259869, 0.00330231, 0.02985044,
        0.06080305, 0.06826296, 0.20770867, 0.20869141, 0.08222262],
       [0.1161295 , 0.01331518, 0.09416594, 0.04731457, 0.03477171,
        0.15460741, 0.1500686 , 0.15162167, 0.03614619, 0.12037017],
       [0.02070627, 0.06657674, 0.07456077, 0.14805428, 0.09545775,
        0.04205135, 0.11448902, 0.17632317, 0.16515932, 0.19161856],
       [0.08380253, 0.03620112, 0.07260872, 0.13304934, 0.11572616,
        0.16236103, 0.18405399, 0.1151999 , 0.08023443, 0.1111568 ],
       [0.0997453 , 0.03342434, 0.0694562

### 5. Заменить значения массива, которые больше 0.5, на -1.

Для наглядности заменим значения в исходном массиве, т.к. в отнормированном массиве все значения меньше 0,5. 

In [7]:
rand_arr[rand_arr>0.5] = -1 # заменим значения массива, которые больше 0.5, на -1

### 6. Вывести полученный массив на экран.

In [8]:
rand_arr # выведем массив на экран 

array([[ 0.01494671,  0.26784111,  0.35879919,  0.45510777,  0.48984194,
        -1.        , -1.        , -1.        , -1.        , -1.        ],
       [ 0.18742289, -1.        ,  0.20361336, -1.        ,  0.19103163,
         0.17244599, -1.        , -1.        ,  0.31279591, -1.        ],
       [ 0.33880104,  0.06812755,  0.24763867,  0.23587707, -1.        ,
        -1.        ,  0.14350379,  0.36638936, -1.        , -1.        ],
       [-1.        , -1.        ,  0.10998635,  0.01684885,  0.13655423,
         0.31830107,  0.3700023 , -1.        , -1.        ,  0.36938285],
       [-1.        ,  0.06301992,  0.45829939,  0.2414054 ,  0.1590671 ,
        -1.        , -1.        , -1.        ,  0.15924636, -1.        ],
       [ 0.11064655,  0.31510357,  0.36288231, -1.        ,  0.43668227,
         0.22013681, -1.        , -1.        , -1.        , -1.        ],
       [ 0.44780935,  0.17133765,  0.35338184, -1.        , -1.        ,
        -1.        , -1.        , -1.        

In [9]:
df = pd.DataFrame(rand_arr) # преобразуем в датафрейм
df # выведем таблицу 

0         1         2         3         4         5         6  \
0  0.014947  0.267841  0.358799  0.455108  0.489842 -1.000000 -1.000000   
1  0.187423 -1.000000  0.203613 -1.000000  0.191032  0.172446 -1.000000   
2  0.338801  0.068128  0.247639  0.235877 -1.000000 -1.000000  0.143504   
3 -1.000000 -1.000000  0.109986  0.016849  0.136554  0.318301  0.370002   
4 -1.000000  0.063020  0.458299  0.241405  0.159067 -1.000000 -1.000000   
5  0.110647  0.315104  0.362882 -1.000000  0.436682  0.220137 -1.000000   
6  0.447809  0.171338  0.353382 -1.000000 -1.000000 -1.000000 -1.000000   
7 -1.000000  0.158195  0.338039  0.390279 -1.000000  0.355918  0.377660   
8 -1.000000  0.264683  0.157351  0.219818  0.244394 -1.000000 -1.000000   
9  0.396339  0.201694 -1.000000 -1.000000 -1.000000 -1.000000  0.362072   

          7         8         9  
0 -1.000000 -1.000000 -1.000000  
1 -1.000000  0.312796 -1.000000  
2  0.366389 -1.000000 -1.000000  
3 -1.000000 -1.000000  0.369383  
4 -1.000000  0.159246 -1.000000  
5 -1.000000 -1.000000 -1.000000  
6 -1.000000  0.353482  0.499369  
7 -1.000000  0.412858 -1.000000  
8  0.399934 -1.000000  0.094279  
9  0.072529 -1.000000 -1.000000